Repository team-wedding/front-end, pull requests merged in 2025-06, with the labels that each got.

#128 Fix/social login
  src/components/login/SocialLogin/KakaoLoginButton.tsx
  src/components/login/SocialLogin/NaverLoginButton.tsx
  src/hooks/useDebounce.tsx
Labels: BugFix

#126 [Feat]head title 아이콘 제목 추가
  index.html
  public/logo_dark.png
Labels: Html&css

#129 Chore/sentry setup
  .gitignore
  package-lock.json
  package.json
  src/actions/invitationAction.ts
  src/components/ResetPassword/ResetPasswordForm.tsx
  src/components/Signup.tsx
  src/components/common/Share/ShareInvitation.tsx
  src/components/display/AttendanceSection/RsvpModal.tsx
  src/components/display/LocationSection/Map.tsx
  src/components/login/EmailLogin/EmailLogin.tsx
  src/components/login/SocialLogin/KakaoRedirect.tsx
  src/components/login/SocialLogin/NaverRedirect.tsx
  src/hooks/useInvitation.tsx
  src/hooks/usePhototalk.tsx
  src/main.tsx
  src/pages/ChangePasswordPage.tsx
  src/pages/EditProfilePage.tsx
  vite.config.ts
Labels: Deploy, Setting

#140 [FIX] refetch 함수
  src/components/common/PhotoTalk/Editor/PhotoTalkEditor.tsx
Labels: BugFix

#142 [Refactor] 포토톡 디자인 수정 및 리팩토링
  src/components/common/Card/Card.tsx
  src/components/common/PhotoTalk/Card/PhotoTalkAction.tsx
  src/components/common/PhotoTalk/Card/PhotoTalkCard.tsx
  src/components/common/PhotoTalk/Card/PhotoTalkImage.tsx
  src/components/common/PhotoTalk/Card/PhotoTalkMessage.tsx
  src/components/common/PhotoTalk/Editor/PhotoTalkEditor.tsx
  src/components/common/PhotoTalk/EmptyState/PhotoTalkEmptyState.tsx
  src/components/common/PhotoTalk/Gallery/PhotoTalkGallery.tsx
  src/components/common/PhotoTalk/Gallery/PhotoTalkGalleryAdmin.tsx
  src/components/common/PhotoTalk/Gallery/PhotoTalkGalleryEmptyState.tsx
  src/components/common/PhotoTalk/Gallery/PhotoTalkGalleryGrid.tsx
  src/components/common/PhotoTalk/Gallery/PhotoTalkGalleryGuest.tsx
  src/components/common/PhotoTalk/Gallery/PhotoTalkGalleryPreview.tsx
  src/components/common/PhotoTalk/List/PhotoTalkCommonList.tsx
  src/components/common/PhotoTalk/List/PhotoTalkListHeader.tsx
  src/components/common/PhotoTalk/List/PhotoTalkListPreview.tsx
  src/components/common/PhotoTalk/Modal/GalleryModal/PhotoTalkGalleryModal.tsx
  src/components/common/PhotoTalk/Modal/GalleryModal/PhotoTalkGalleryModalFooter.tsx
  src/components/common/Skeleton/SkeletonPhotoTalk.tsx
  src/components/common/Tab/Tab.tsx
  src/components/icons/BackIcon.tsx
  src/components/icons/Chevron_LeftIcon.tsx
  src/components/icons/Chevron_RightIcon.tsx
  src/components/icons/DownloadIcon.tsx
  src/components/icons/ImageIcon.tsx
  src/components/icons/MenuDotsIcon.tsx
  src/components/icons/TrashIcon.tsx
  src/components/layout/PhotoTalkLayout.tsx
  src/constants/phototalkData.tsx
  src/hooks/useDropDown.tsx
  src/hooks/usePhototalk.tsx
  src/pages/DashBoardPage.tsx
  src/pages/PhotoTalk/AdminPhotoTalkPage.tsx
  src/pages/PhotoTalk/GuestPhotoTalkPage.tsx
  src/pages/PhotoTalk/PreviewPhotoTalkPage.tsx
  src/pages/PreviewInvitationPage.tsx
  src/styles/global.css
  tailwind.config.js
Labels: Html&css, Refactor

#124 [FIX] : create cancel modal
  build.sh
  src/actions/invitationAction.ts
  src/components/common/CreateInvitation/PreviewButton.tsx
  src/main.tsx
  src/pages/CreateInvitationPage.tsx
  src/pages/NotFound404.tsx
Labels: BugFix

#153 [Feature] 포토톡 수정 기능 구현 & 에디터 리팩토링
  index.html
  src/components/common/Card/Card.tsx
  src/components/common/PhotoTalk/Editor/PhotoTalkEditor.tsx
  src/components/layout/PhotoTalkLayout.tsx
  src/components/login/Signup.tsx
  src/components/mypage/EditMyPage/LogoutModal.tsx
  src/components/mypage/EditMyPage/WithdrawModal.tsx
  src/components/mypage/ResetPassword/ResetPasswordButton.tsx
  src/components/mypage/ResetPassword/ResetPasswordForm.tsx
  src/components/mypage/ResetPassword/TemporaryPasswordModal.tsx
  src/components/phototalk/Card/PhotoTalkAction.tsx
  src/components/phototalk/Card/PhotoTalkCard.tsx
  src/components/phototalk/Card/PhotoTalkImage.tsx
  src/components/phototalk/Card/PhotoTalkMessage.tsx
  src/components/phototalk/Editor/PhotoTalkEditor.tsx
  src/components/phototalk/Editor/PhotoTalkImageUpload.tsx
  src/components/phototalk/EmptyState/PhotoTalkEmptyState.tsx
  src/components/phototalk/Gallery/PhotoTalkGallery.tsx
  src/components/phototalk/Gallery/PhotoTalkGalleryAdmin.tsx
  src/components/phototalk/Gallery/PhotoTalkGalleryGrid.tsx
  src/components/phototalk/Gallery/PhotoTalkGalleryGuest.tsx
  src/components/phototalk/Gallery/PhotoTalkGalleryPreview.tsx
  src/components/phototalk/List/PhotoTalkCommonList.tsx
  src/components/phototalk/List/PhotoTalkListAdmin.tsx
  src/components/phototalk/List/PhotoTalkListEmptyState.tsx
  src/components/phototalk/List/PhotoTalkListGuest.tsx
  src/components/phototalk/List/PhotoTalkListHeader.tsx
  src/components/phototalk/List/PhotoTalkListPreview.tsx
  src/components/phototalk/Modal/GalleryModal/PhotoTalkGalleryModal.tsx
  src/components/phototalk/Modal/GalleryModal/PhotoTalkGalleryModalFooter.tsx
  src/components/phototalk/Modal/PasswordConfirmModal.tsx
  src/hooks/usePhototalk.tsx
  src/hooks/usePhototalkAction.tsx
  src/hooks/useS3Image.tsx
  src/pages/ChangePasswordPage.tsx
  src/pages/CreateInvitationPage.tsx
  src/pages/EditProfilePage.tsx
  src/pages/PhotoTalk/AdminPhotoTalkPage.tsx
  src/pages/PhotoTalk/GuestPhotoTalkPage.tsx
  src/pages/PhotoTalk/PreviewPhotoTalkPage.tsx
  src/pages/ResetPasswordPage.tsx
  src/pages/SignUpPage.tsx
  src/services/imageService.tsx
  src/types/invitationType.d.ts
  src/types/s3Type.d.ts
  src/utils/config.ts
Labels: API, Feature

#158 [Feature] Storybook
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  eslint.config.js
  package-lock.json
  package.json
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: Setting
